services:
  nginx-proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      isleblue_network:
        aliases:
          - isleblue_nginx
      isleblue_api_network:
        aliases:
          - isleblue_api_nginx
      isleblue_manage_network:
        aliases:
          - isleblue_manage_nginx    
      backend:
        aliases:
          - reverse_proxy

networks:
  isleblue_network:
    external: true
    name: isleblue_default
  isleblue_api_network:
    external: true
    name: isleblueapi_default
  isleblue_manage_network:
    external: true
    name: islebluemanage_default  
  backend:
    external: true
    name: backend