services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: isleblue_nginx
    depends_on:
      - php
      - mysql
      - redis
    volumes:
      - ./src:/var/www/html    
    networks:
      - default
      - backend  

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        user: laravel
        uid: ${UID:-1000}
    container_name: isleblue_php
    volumes:
      - ./src:/var/www/html  
    networks:
      - default
      - backend  

  mysql:
    image: mariadb:10.11
    container_name: isleblue_mysql
    env_file:
      - .env
    ports:
      - "3312:3312"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  composer:
    image: composer:latest
    container_name: isleblue_composer
    user: ${UID:-1000}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html  

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        user: laravel
        uid: ${UID:-1000}
    container_name: isleblue_artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - default
      - backend

  npm:
    image: node:22
    container_name: isleblue_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: ${UID:-1000}
    entrypoint: ["npm"]

  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        user: laravel
        uid: ${UID:-1000}
    container_name: isleblue_phpunit
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]

  redis:
    image: redis:latest
    container_name: isleblue_redis
    ports:
      - 6376:6376

  scheduler:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        user: laravel
        uid: ${UID:-1000}
    container_name: isleblue_scheduler
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "schedule:work"]

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: isleblue_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - 8083:80
        
volumes:
  mysql:

networks:
  default: {}
  backend:
    external: true
